dotenv: .env
networks:
  default: development
  rinkeby:
    url: https://rinkeby.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    accounts:
      - ${PRIVATE_KEY}
  kovan:
    url: https://kovan.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    accounts:
      - ${PRIVATE_KEY}
  ropsten:
    url: https://ropsten.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
    accounts:
      - ${PRIVATE_KEY}
  goerli:
    link_token: '0x326C977E6efc84E512bB9C30f76E30c160eD06FB'
    url: https://goerli.infura.io/v3/${WEB3_INFURA_PROJECT_ID}  # Replace with your RPC URL for Goerli
    accounts:
      - ${PRIVATE_KEY}
compiler:
  solc:
    version: 0.8.7
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.4.0
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
wallets:
  from_key: ${PRIVATE_KEY}
